spring.datasource.url=${GAME_DB_URL:jdbc:postgresql://127.0.0.1:54329/game_db}
spring.datasource.username=${GAME_DB_USER:poker}
spring.datasource.password=${GAME_DEV_DB_PASSWORD:poker_dev}
spring.rabbitmq.port=${RABBITMQ_PORT:56729}
server.address=127.0.0.1
