include:
  - docker/compose.infra.yml
  - api-gateway/compose.yml
  - identity-service/compose.yml
  - game-service/compose.yml
  - matchmaking-service/compose.yml
  - social-service/compose.yml
  - chat-service/compose.yml
  - ranking-service/compose.yml
  - competition-service/compose.yml
  - shop-service/compose.yml
  - wallet-service/compose.yml
