services:
  game-service:
    ports: !override
      - "127.0.0.1:8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_ADDRESS: 0.0.0.0
      RABBITMQ_PORT: 5672
      GAME_DEV_DB_PASSWORD: ${GAME_DB_PASSWORD:-poker_dev}
