package com.msspoker.gameservice.exception;

public enum GameError {
    GAME_NOT_FOUND, GAME_FORBIDDEN, GAME_PLAYER_BUSY, GAME_SOURCE_CONFLICT,
    GAME_INVALID_REQUEST, GAME_INVALID_ACTION, GAME_CONFLICT, GAME_DEPENDENCY_UNAVAILABLE,
    GAME_UNAUTHORIZED, GAME_INTERNAL_ERROR
}
